// src/paws/pawdev/report.ts
//
// REPORT for paw-dev-cycle. Deterministic: the numbers come from the collector
// payload, the cards and repo_events, so the routine cannot report work it did
// not do. The text goes into the daily digest through the ordinary paw send.

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { RepoEvent } from '../../repo-events.js'
import type { GithubDevRaw } from '../collectors/github-dev.js'

export interface RepoLine {
  repo: string
  fresh: number
  coded: number
  waiting: number
  shipped: number
}

export function repoLines(
  raw: GithubDevRaw,
  cards: Array<{ status: string; source: string }>,
  events: RepoEvent[],
): RepoLine[] {
  return raw.repos.map((r) => {
    const mine = cards.filter(c => c.source === `github:${r.repo}`)
    return {
      repo: r.repo,
      fresh: r.new_issues.length + r.new_prs.length,
      coded: mine.filter(c => c.status === 'in_progress').length,
      waiting: mine.filter(c => c.status === 'blocked').length,
      shipped: mine.filter(c => c.status === 'completed').length
        + events.filter(e => e.repo === r.repo && e.kind === 'pr_merged').length,
    }
  })
}

export function renderReport(lines: RepoLine[]): string {
  if (lines.length === 0) return 'No repo activity this cycle.'
  return lines
    .map(l => `${l.repo}: ${l.fresh} new, ${l.coded} coded, ${l.waiting} waiting on you, ${l.shipped} shipped`)
    .join('\n')
}

// A repo name, ref or actor is free text from GitHub, not from us. A `|` or a
// newline in it would break out of its table cell and forge a row. Replace
// each with a space rather than reject the row: the export is a log, not a
// gate, so a weird ref still shows up, just not as a table row it did not earn.
function cell(value: string): string {
  return value.replace(/[\r\n|]/g, ' ')
}

export function renderHistoryMarkdown(
  events: RepoEvent[],
  stats: Array<{ repo: string; kind: string; actor_class: string; n: number }>,
  generatedAt: number,
): string {
  const stamp = new Date(generatedAt).toISOString()
  const rows = events.map(e =>
    `| ${new Date(e.created_at).toISOString().slice(0, 16).replace('T', ' ')} | ${cell(e.repo)} | ${cell(e.kind)} | ${cell(e.ref ?? '')} | ${cell(e.actor)} |`)
  const statRows = stats.map(s => `| ${cell(s.repo)} | ${cell(s.kind)} | ${cell(s.actor_class)} | ${s.n} |`)
  return [
    '# Paw Dev history',
    '',
    `Generated from the repo_events table at ${stamp}. Do not edit this file.`,
    'The table is the source, this export exists so the history is visible in git.',
    'A contributor pull request can appear twice, once as the reviewer\'s issue ref and once as the builder\'s PR url.',
    '',
    '## Counts',
    '',
    '| repo | kind | who | n |',
    '|---|---|---|---|',
    ...statRows,
    '',
    '## Events',
    '',
    '| when (UTC) | repo | kind | ref | actor |',
    '|---|---|---|---|---|',
    ...rows,
    '',
  ].join('\n')
}

export function writeHistoryFile(markdown: string, root: string): string {
  const path = join(root, 'docs', 'paw-dev', 'HISTORY.md')
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, markdown, 'utf-8')
  return path
}
